<a href="https://colab.research.google.com/github/whdigrace/kfq_ML_2023/blob/main/CH2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import sklearn

In [ ]:
help(sklearn)

Help on package sklearn:

NAME
    sklearn

DESCRIPTION
    Machine learning module for Python
    
    sklearn is a Python module integrating classical machine
    learning algorithms in the tightly-knit world of scientific Python
    packages (numpy, scipy, matplotlib).
    
    It aims to provide simple and efficient solutions to learning problems
    that are accessible to everybody and reusable in various contexts:
    machine-learning as a versatile tool for science and engineering.
    
    See http://scikit-learn.org for complete documentation.

PACKAGE CONTENTS
    __check_build (package)
    _build_utils (package)
    _config
    _distributor_init
    _isotonic
    _loss (package)
    _min_dependencies
    base
    calibration
    cluster (package)
    compose (package)
    conftest
    covariance (package)
    cross_decomposition (package)
    datasets (package)
    decomposition (package)
    discriminant_analysis
    dummy
    ensemble (package)
    exceptions
    experime

In [5]:
print(sklearn.__version__)

1.2.2


## 첫 번째 머신러닝-붓꽃 품종 예측하기


In [16]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [17]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [18]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [19]:
iris_data = iris.data
iris_data.shape

(150, 4)

In [20]:
iris_label=iris.target

In [21]:
import numpy as np
np.unique(iris_label,return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

In [22]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [31]:
df = pd.DataFrame(iris.data, columns  = iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [29]:
xa = [[x,x]for x in range(100)]
ya = [y for y in range(100)]

In [30]:
x_train,x_test,y_train,y_test = train_test_split(xa,ya)

In [32]:
np.array(x_train).shape, np.array(y_train).shape

((75, 2), (75,))

In [33]:
for i in range(len(x_train)):
  print(x_train[i], ":",y_train[i])

[83, 83] : 83
[10, 10] : 10
[34, 34] : 34
[41, 41] : 41
[42, 42] : 42
[96, 96] : 96
[53, 53] : 53
[66, 66] : 66
[9, 9] : 9
[67, 67] : 67
[89, 89] : 89
[72, 72] : 72
[3, 3] : 3
[77, 77] : 77
[90, 90] : 90
[79, 79] : 79
[30, 30] : 30
[85, 85] : 85
[92, 92] : 92
[86, 86] : 86
[8, 8] : 8
[6, 6] : 6
[59, 59] : 59
[1, 1] : 1
[69, 69] : 69
[88, 88] : 88
[87, 87] : 87
[93, 93] : 93
[55, 55] : 55
[0, 0] : 0
[22, 22] : 22
[91, 91] : 91
[45, 45] : 45
[16, 16] : 16
[64, 64] : 64
[74, 74] : 74
[11, 11] : 11
[46, 46] : 46
[18, 18] : 18
[24, 24] : 24
[51, 51] : 51
[29, 29] : 29
[76, 76] : 76
[44, 44] : 44
[82, 82] : 82
[19, 19] : 19
[73, 73] : 73
[48, 48] : 48
[62, 62] : 62
[5, 5] : 5
[52, 52] : 52
[80, 80] : 80
[23, 23] : 23
[78, 78] : 78
[47, 47] : 47
[63, 63] : 63
[26, 26] : 26
[38, 38] : 38
[36, 36] : 36
[15, 15] : 15
[13, 13] : 13
[94, 94] : 94
[97, 97] : 97
[81, 81] : 81
[75, 75] : 75
[33, 33] : 33
[68, 68] : 68
[32, 32] : 32
[98, 98] : 98
[40, 40] : 40
[71, 71] : 71
[50, 50] : 50
[61, 61] : 61

In [57]:
x_train,x_test,y_train,y_test= train_test_split(
    iris_data,iris_label,test_size=0.2)

In [58]:
x_train.shape,x_test.shape

((120, 4), (30, 4))

In [59]:
print(y_train)

[0 1 2 2 0 0 0 0 0 2 2 0 1 2 0 0 2 0 0 0 2 1 0 2 0 0 2 0 1 2 2 0 1 1 2 1 2
 2 2 1 1 0 2 1 2 0 1 2 1 1 2 1 2 0 2 0 1 2 1 2 0 2 0 0 0 1 1 2 2 1 1 1 1 1
 1 1 2 2 1 2 2 0 1 1 2 2 0 2 0 0 1 1 2 2 1 1 2 1 0 0 1 2 2 2 0 0 0 2 2 2 0
 0 0 1 1 0 1 1 1 0]


In [62]:
model = DecisionTreeClassifier() # 모델 생성
model.fit(x_train, y_train) # 모델 학습(머신러닝 모델에서 기계학습은 fit 사용)

DecisionTreeClassifier()

In [63]:
pred = model.predict(x_test) # 학습한 모델로 예측->모델 학습 결과 평가

In [64]:
for i in range(len(pred)):
  print(pred[i], ':', y_test[i])

print(pred)
print(y_test)

0 : 0
2 : 2
1 : 1
0 : 0
2 : 2
2 : 2
1 : 1
0 : 0
1 : 1
0 : 0
2 : 2
0 : 0
1 : 1
1 : 1
2 : 2
0 : 0
1 : 1
1 : 1
2 : 1
0 : 0
2 : 2
2 : 2
1 : 1
0 : 0
0 : 0
1 : 1
2 : 2
0 : 0
0 : 0
1 : 1
[0 2 1 0 2 2 1 0 1 0 2 0 1 1 2 0 1 1 2 0 2 2 1 0 0 1 2 0 0 1]
[0 2 1 0 2 2 1 0 1 0 2 0 1 1 2 0 1 1 1 0 2 2 1 0 0 1 2 0 0 1]


In [65]:
from sklearn.metrics import accuracy_score # 적합도 검정

In [66]:
print('예측 정확도 :', accuracy_score(y_test, pred)) # 모델 평가

예측 정확도 : 0.9666666666666667


In [70]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [71]:
keys = iris_data.keys()

In [73]:
print("특성:",iris_data.feature_names)

특성: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [74]:
print("특성 수:", len(iris_data.feature_names))

특성 수: 4


In [76]:
print("종속 변수 타입:", type(iris_data.target[0]))

종속 변수 타입: <class 'numpy.int64'>


In [78]:
print("타겟 이름:",iris_data.target_names)

타겟 이름: ['setosa' 'versicolor' 'virginica']


In [79]:
print("독립변수 구조:",iris_data.data.shape)

독립변수 구조: (150, 4)


In [80]:
print("종속변수 타입:",type(iris_data.target[0]))

종속변수 타입: <class 'numpy.int64'>


# Model Selection 모듈 소개

In [81]:
iris = load_iris()
train_data = iris.data #독립변수(data.feature.x)
train_label = iris.target #종속변수(label.target.y)


In [83]:
df = DecisionTreeClassifier()
df.fit(train_data,train_label)
pred = df.predict(train_data)
accuracy_score(pred,train_label)

1.0

In [84]:
x_train,x_test,y_train,y_test= train_test_split(
    iris.data,iris.target
)

In [85]:
model = DecisionTreeClassifier() #모델 생성
model.fit(x_train,y_train) #모델 학습
pred = model.predict(x_test) #예측
accuracy_score(y_test,pred) #평가

0.8947368421052632

In [88]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [97]:
iris = load_iris()
feature = iris.data
label = iris.target
dt = DecisionTreeClassifier()

In [98]:
kfold = KFold(n_splits=5)
cv_accuracy= []
n_iter = 0 #반복 횟수

In [99]:
for train_ind, val_ind in kfold.split(feature):
  x_train, x_val = feature[train_ind], feature[val_ind]
  y_train, y_val = label[train_ind], label[val_ind]

  df.fit(x_train, y_train) #학습
  pred = df.predict(x_val)  #예측
  n_iter += 1 # 반복 횟수 1씩 증가
  acc = np.round(accuracy_score(pred, y_val),3)
  print(n_iter, '회 교차 검증 accuracy:', acc)
  cv_accuracy.append(acc)
  print('평균 accuracy:', np.mean(cv_accuracy))


1 회 교차 검증 accuracy: 1.0
평균 accuracy: 1.0
2 회 교차 검증 accuracy: 0.967
평균 accuracy: 0.9835
3 회 교차 검증 accuracy: 0.833
평균 accuracy: 0.9333333333333332
4 회 교차 검증 accuracy: 0.933
평균 accuracy: 0.9332499999999999
5 회 교차 검증 accuracy: 0.833
평균 accuracy: 0.9132


In [101]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['label']=iris.target
df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [103]:
kfold = KFold(n_splits=3)
n_iter = 0
for train_ind,val_ind in kfold.split(df):
  label_train = df['label'].iloc[train_ind]
  label_val = df['label'].iloc[val_ind]
  n_iter+=1
  print(n_iter,"====")
  print("학습데이터:",label_train.value_counts())
  print("검증데이터:",label_val.value_counts())

1 ====
학습데이터: 1    50
2    50
Name: label, dtype: int64
검증데이터: 0    50
Name: label, dtype: int64
2 ====
학습데이터: 0    50
2    50
Name: label, dtype: int64
검증데이터: 1    50
Name: label, dtype: int64
3 ====
학습데이터: 0    50
1    50
Name: label, dtype: int64
검증데이터: 2    50
Name: label, dtype: int64


In [104]:
dt = DecisionTreeClassifier()
kfold = KFold(n_splits=3)
n_iter = 0
xdf = df.drop('label',axis=1)
for train_ind,val_ind in kfold.split(df):
  x_train = xdf.iloc[train_ind]
  x_val = xdf.iloc[val_ind]
  label_train = df['label'].iloc[train_ind]
  label_val = df['label'].iloc[val_ind]
  dt.fit(x_train,label_train) #학습
  pred = dt.predict(x_val) #예측
  n_iter+=1
  acc = np.round(accuracy_score(pred,label_val),3)
  print(n_iter,"====")
  print("학습 데이터:",label_train.value_counts())
  print("검증 데이터:",label_val.value_counts())
  print("평가 accuracy:",acc)

1 ====
학습 데이터: 1    50
2    50
Name: label, dtype: int64
검증 데이터: 0    50
Name: label, dtype: int64
평가 accuracy: 0.0
2 ====
학습 데이터: 0    50
2    50
Name: label, dtype: int64
검증 데이터: 1    50
Name: label, dtype: int64
평가 accuracy: 0.0
3 ====
학습 데이터: 0    50
1    50
Name: label, dtype: int64
검증 데이터: 2    50
Name: label, dtype: int64
평가 accuracy: 0.0


In [105]:
from sklearn.model_selection import StratifiedKFold

In [106]:
dt = DecisionTreeClassifier()
kfold = KFold(n_splits=3)
n_iter = 0
xdf = df.drop('label',axis=1)
for train_ind,val_ind in kfold.split(df,xdf):
  x_train = xdf.iloc[train_ind]
  x_val = xdf.iloc[val_ind]
  label_train = df['label'].iloc[train_ind]
  label_val = df['label'].iloc[val_ind]
  dt.fit(x_train,label_train) #학습
  pred = dt.predict(x_val) #예측
  n_iter+=1
  acc = np.round(accuracy_score(pred,label_val),3)
  print(n_iter,"====")
  print("학습 데이터:",label_train.value_counts())
  print("검증 데이터:",label_val.value_counts())
  print("평가 accuracy:",acc)

1 ====
학습 데이터: 1    50
2    50
Name: label, dtype: int64
검증 데이터: 0    50
Name: label, dtype: int64
평가 accuracy: 0.0
2 ====
학습 데이터: 0    50
2    50
Name: label, dtype: int64
검증 데이터: 1    50
Name: label, dtype: int64
평가 accuracy: 0.0
3 ====
학습 데이터: 0    50
1    50
Name: label, dtype: int64
검증 데이터: 2    50
Name: label, dtype: int64
평가 accuracy: 0.0


In [107]:
from sklearn.model_selection import cross_val_score, cross_validate


In [108]:
data = iris.data
label = iris.target

In [110]:
dt = DecisionTreeClassifier()
scores = cross_val_score(dt,data,label,scoring='accuracy',cv=3) #cv는 kfold갯수
scores

array([0.98, 0.92, 0.98])

In [111]:
dt = DecisionTreeClassifier()
scores = cross_val_score(dt,data,label,scoring=['accuracy','precision','recall'],
                         cv=3)
scores

ValueError: ignored

In [112]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target)

In [113]:
mds = [1,2,3]
for depth in mds:
  dt = DecisionTreeClassifier(max_depth=depth)
  dt.fit(x_train,y_train)
  pred = dt.predict(x_test)
  print(depth,"acc=",accuracy_score(y_test,pred))

1 acc= 0.7105263157894737
2 acc= 0.9473684210526315
3 acc= 0.9736842105263158


In [114]:
mds = [1,2,3]
mss = [2,3,4]
for depth in mds:
  for ms in mss:
    dt = DecisionTreeClassifier(max_depth=depth,min_samples_split=ms)
    dt.fit(x_train,y_train)
    pred = dt.predict(x_test)
    print(depth,",",ms,": acc =",accuracy_score(y_test,pred))

1 , 2 : acc = 0.7105263157894737
1 , 3 : acc = 0.7105263157894737
1 , 4 : acc = 0.7105263157894737
2 , 2 : acc = 0.9473684210526315
2 , 3 : acc = 0.9473684210526315
2 , 4 : acc = 0.9473684210526315
3 , 2 : acc = 0.9736842105263158
3 , 3 : acc = 0.9736842105263158
3 , 4 : acc = 0.9736842105263158


In [115]:
params = {
    'max_depth':[1,2,3],
    'min_samples_split':[2,3,4]
}

In [116]:
from sklearn.model_selection import GridSearchCV

In [118]:
dt = DecisionTreeClassifier()
gs = GridSearchCV(dt,param_grid=params,cv=3,refit=True)
gs.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3],
                         'min_samples_split': [2, 3, 4]})

In [119]:
gs.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [120]:
gs.best_score_

0.9374110953058322

In [121]:
model = gs.best_estimator_

In [122]:
pred = model.predict(x_test)
accuracy_score(y_test,pred)

0.9473684210526315

# 전처리

In [123]:
from sklearn.preprocessing import LabelEncoder

In [125]:
items = ['TV','냉장고',
         '전자레인지','컴퓨터',
         '선풍기','선풍기',
         '믹서','믹서']

In [127]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [129]:
items2 = ['TV','TV','냉장고','선풍기']
labels = encoder.transform(items2)
labels

array([0, 0, 1, 3])

In [131]:
items3 = ['식기세척기','스타일러','슈즈스타일러']
labels = encoder.transform(items3)
labels

ValueError: ignored

In [132]:
from sklearn.preprocessing import OneHotEncoder

In [133]:
np.array(items).reshape(-1,1)

array([['TV'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [135]:
ohe = OneHotEncoder()
ohe.fit(items)
labels=ohe.transform(items)
labels.torray()

ValueError: ignored

In [136]:
from scipy import stats

In [139]:
heights = stats.norm.rvs(loc=173,scale=4,size=1000)
bmis = stats.norm.rvs(loc=21,scale=2,size=1000)
weights=bmis*(heights**2)/10000

In [140]:
c_sizes = [ (heights[i]*2+weights[i]*2)/5  for i in range(1000)]
c_sizes = np.array(c_sizes)

In [141]:
from sklearn.neighbors import KNeighborsRegressor
df = pd.DataFrame()
df['height'] = heights
df['weight'] = weights
data = df.values


In [142]:
label = c_sizes

In [143]:
x_train, x_test, y_train, y_test = train_test_split(data,label)

In [144]:
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)


KNeighborsRegressor()

In [145]:
knn.score(x_test,y_test)

0.9933993805292431

In [147]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [149]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [ ]:
df.var()

In [151]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [154]:
ss = StandardScaler()
ss.fit(df)
scaled = ss.transform(df)
np.round(scaled.mean(),10), scaled.var()

(-0.0, 1.0)

In [156]:
df2 = pd.DataFrame(scaled)
filter = df2[0]<3
filter.value_counts()

True    150
Name: 0, dtype: int64

In [157]:
df2.describe()

0             1             2             3
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -1.468455e-15 -1.823726e-15 -1.610564e-15 -9.473903e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.433947e+00 -1.567576e+00 -1.447076e+00
25%   -9.006812e-01 -5.923730e-01 -1.226552e+00 -1.183812e+00
50%   -5.250608e-02 -1.319795e-01  3.364776e-01  1.325097e-01
75%    6.745011e-01  5.586108e-01  7.627583e-01  7.906707e-01
max    2.492019e+00  3.090775e+00  1.785832e+00  1.712096e+00

In [158]:
mms = MinMaxScaler()
mms.fit(df)
scaled = mms.transform(df)
df3 = pd.DataFrame(scaled)
df3.describe()

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     0.428704    0.440556    0.467458    0.458056
std      0.230018    0.181611    0.299203    0.317599
min      0.000000    0.000000    0.000000    0.000000
25%      0.222222    0.333333    0.101695    0.083333
50%      0.416667    0.416667    0.567797    0.500000
75%      0.583333    0.541667    0.694915    0.708333
max      1.000000    1.000000    1.000000    1.000000

In [160]:
mms = MinMaxScaler()
mms.fit(data)
scaled_data = mms.transform(data)

x_train, x_test, y_train, y_test = train_test_split(scaled_data,label)
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.9942755367890098

In [161]:
x_train, x_test, y_train, y_test = train_test_split(data,label)

In [166]:
mms1 = MinMaxScaler()
mms1.fit(x_train)
scaled_train = mms1.transform(x_train)

In [167]:
mms2 = MinMaxScaler()
mms2.fit(x_test)
scaled_test = mms2.transform(x_test)


In [168]:
sample = [[1.75,89],[1.72,62]]
mms1.transform(sample)

array([[-5.23915288,  1.13091347],
       [-5.24016395,  0.50969437]])

In [169]:
mms2.transform(sample)

array([[-8.194272  ,  1.10153996],
       [-8.19580112,  0.4167858 ]])